name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # الخطوة 1: تحقق من الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v3
      
      # الخطوة 2: إعداد البيئة (مثل تثبيت الأدوات اللازمة)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      # الخطوة 3: تثبيت التبعيات
      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            yarn install
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            npm install
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      # الخطوة 4: تشغيل الاختبارات
      - name: Run tests
        run: |
          if [ "$manager" == "yarn" ]; then
            yarn test
          elif [ "$manager" == "npm" ]; then
            npm test
          fi

      # الخطوة 5: بناء المشروع (إذا لزم الأمر)
      - name: Build project
        run: |
          if [ "$manager" == "yarn" ]; then
            yarn build
          elif [ "$manager" == "npm" ]; then
            npm run build
          fi

      # الخطوة 6: نشر المشروع (اختياري، بناءً على الحاجة)
      - name: Deploy project
        run: |
          echo "Deploying project..."
          # أضف هنا خطوات النشر الخاصة بك

    env:
      BUILD_PATH: .
